apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80 #nginx is exposed on this port insider the container
        env:
         - name: ABC_VALUE  # Environment variable name
           valueFrom:
            configMapKeyRef:
              name: nginx-config  # Refers to the ConfigMap created above
              key: abc  # The key in the ConfigMap